"""
Script to append new v2 pipeline cells to the existing DOAR notebook.
Run once. Safe — never modifies existing cells.
"""
import json, sys, os

NB_PATH = os.path.join(os.path.dirname(__file__), "DOAR_QA_30_04_26 (2).ipynb")

# ── New cells to append ────────────────────────────────────────────────────

CELL_SEPARATOR = {
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "---\n",
        "## PART G — DOAR v2 Pipeline\n",
        "### Claim-based validation, extended psychological rules, parent helper, final judge\n",
        "\n",
        "The cells below add the v2 pipeline. They **do not modify** Parts A–F.\n",
        "Run Parts A–F first (or load a cached doc), then run these cells.\n",
    ]
}

CELL_SETUP = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# ════════════════════════════════════════════════════════════════\n",
        "# PART G-0 — v2 Module Setup\n",
        "# ════════════════════════════════════════════════════════════════\n",
        "import sys, os\n",
        "\n",
        "# Add src/ to path so v2 modules are importable\n",
        "_REPO_ROOT = os.path.dirname(os.path.abspath('__file__')) if '__file__' in dir() else '/content'\n",
        "# If running on Colab, src/ may be under /content/DOAR/src or mounted drive\n",
        "# Adjust this path if needed:\n",
        "_SRC_PATHS = [\n",
        "    os.path.join(_REPO_ROOT, 'src'),\n",
        "    '/content/DOAR/src',\n",
        "    '/content/drive/MyDrive/Masters/DOAR_Project_30_4_26_V2/src',\n",
        "]\n",
        "for _p in _SRC_PATHS:\n",
        "    if os.path.isdir(_p) and _p not in sys.path:\n",
        "        sys.path.insert(0, _p)\n",
        "        print(f'[v2 Setup] Added to path: {_p}')\n",
        "        break\n",
        "\n",
        "# Import all v2 modules\n",
        "from safety_policy          import GENERAL_DISCLAIMER, check_for_diagnostic_language\n",
        "from psychological_rules_v2 import evaluate_v2_rules, compute_theme_scores\n",
        "from emotion_heuristic      import estimate_emotional_tendency\n",
        "from claim_builder          import build_all_claims, build_theme_claims\n",
        "from numeric_validator      import validate_all_numeric_claims\n",
        "from visual_claim_validator import validate_all_visual_claims\n",
        "from ocr_validator          import validate_all_ocr_claims\n",
        "from psych_safety_validator import validate_all_psych_claims, build_validation_summary\n",
        "from parent_ai_helper       import generate_parent_answer\n",
        "from final_response_judge   import judge_final_response\n",
        "\n",
        "print('[v2 Setup] All v2 modules loaded successfully.')\n",
    ]
}

CELL_RULES_V2 = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# ════════════════════════════════════════════════════════════════\n",
        "# PART G-1 — Extended Psychological Rules (v2)\n",
        "# Tier 1: composition/placement/size (objective features)\n",
        "# Tier 2: symbolic/projective (animals, shapes, eyes) — lower weight\n",
        "# ════════════════════════════════════════════════════════════════\n",
        "\n",
        "def run_v2_rules(doc, quality_score=None):\n",
        "    \"\"\"\n",
        "    Evaluate all v2 rules against a populated doc dict.\n",
        "    Adds 'psychological_rule_activations_v2' and 'theme_scores_v2' to doc.\n",
        "    \"\"\"\n",
        "    if quality_score is None:\n",
        "        quality_score = doc.get('image_quality', {}).get('quality_score', 1.0)\n",
        "\n",
        "    activations = evaluate_v2_rules(doc, quality_score)\n",
        "    doc['psychological_rule_activations_v2'] = activations\n",
        "\n",
        "    activated_ids  = [r['rule_id'] for r in activations if r['activated']]\n",
        "    rule_conf_map  = {r['rule_id']: r['rule_confidence'] for r in activations}\n",
        "    theme_scores   = compute_theme_scores(activated_ids, rule_conf_map)\n",
        "    doc['theme_scores_v2'] = theme_scores\n",
        "\n",
        "    # Print summary\n",
        "    n_active = len(activated_ids)\n",
        "    print(f'[v2 Rules] {n_active} rule(s) activated out of {len(activations)}.')\n",
        "    for r in activations:\n",
        "        if r['activated']:\n",
        "            tier   = r['tier']\n",
        "            eid    = r['evidence_strength']\n",
        "            conf   = r['rule_confidence']\n",
        "            print(f'  [{tier}] {r[\"rule_id\"]:40s}  conf={conf:.3f}  ({eid})')\n",
        "    if theme_scores:\n",
        "        print(f'[v2 Rules] {len(theme_scores)} theme(s) emerged:')\n",
        "        for t in theme_scores:\n",
        "            print(f'  THEME: {t[\"theme\"]:40s}  score={t[\"theme_score\"]:.3f}')\n",
        "    else:\n",
        "        print('[v2 Rules] No themes met the minimum cluster threshold.')\n",
        "    return doc\n",
        "\n",
        "print('[G-1] v2 rule evaluator defined.')\n",
    ]
}

CELL_EMOTION = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# ════════════════════════════════════════════════════════════════\n",
        "# PART G-2 — Feature-Based Emotional Tendency (Heuristic Fallback)\n",
        "# ── NOT a trained model prediction ──────────────────────────────\n",
        "# ════════════════════════════════════════════════════════════════\n",
        "\n",
        "def run_emotion_heuristic(doc):\n",
        "    \"\"\"\n",
        "    Add heuristic emotional tendency estimate to doc.\n",
        "    Clearly labelled as method='heuristic', confidence='low'.\n",
        "    Must NOT be presented as a trained model output.\n",
        "    \"\"\"\n",
        "    result = estimate_emotional_tendency(doc)\n",
        "    doc.update(result)  # adds 'feature_based_emotional_tendency' key\n",
        "    h = result['feature_based_emotional_tendency']\n",
        "    print('[G-2] Heuristic emotional tendency estimate:')\n",
        "    print(f'  estimated_emotion : {h[\"estimated_emotion\"]}')\n",
        "    print(f'  confidence_label  : {h[\"confidence_label\"]}')\n",
        "    print(f'  method            : {h[\"method\"]}')\n",
        "    print(f'  WARNING           : {h[\"display_warning\"]}')\n",
        "    return doc\n",
        "\n",
        "print('[G-2] Emotion heuristic function defined.')\n",
    ]
}

CELL_CLAIMS = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# ════════════════════════════════════════════════════════════════\n",
        "# PART G-3 — Claim Builder + Validation Pipeline\n",
        "# Numeric → Visual → OCR → Psych safety validators\n",
        "# ════════════════════════════════════════════════════════════════\n",
        "\n",
        "def run_claim_pipeline(doc, image_path,\n",
        "                       clip_model=None, clip_preprocess=None, clip_tokenize=None):\n",
        "    \"\"\"\n",
        "    Build all claims from doc and run the full validation pipeline.\n",
        "    Returns validated claims list and adds 'validated_claims' + 'validation_summary' to doc.\n",
        "    \"\"\"\n",
        "    print('[G-3] Building claims...')\n",
        "\n",
        "    # Merge v2 theme claims\n",
        "    themes = doc.get('theme_scores_v2', [])\n",
        "    raw_claims = build_all_claims(doc)\n",
        "    from claim_builder import build_theme_claims as _btc\n",
        "    raw_claims += _btc(themes)\n",
        "\n",
        "    print(f'[G-3] {len(raw_claims)} raw claims built.')\n",
        "\n",
        "    # Step 1: Numeric validation\n",
        "    claims = validate_all_numeric_claims(raw_claims)\n",
        "    n_num_verified = sum(1 for c in claims\n",
        "                         if c.get('claim_type') == 'visual_numeric'\n",
        "                         and c.get('validator_status') == 'verified')\n",
        "    print(f'[G-3] Numeric validation: {n_num_verified} numeric claims verified.')\n",
        "\n",
        "    # Step 2: Visual claim validation (CLIP)\n",
        "    claims = validate_all_visual_claims(\n",
        "        claims, image_path, clip_model, clip_preprocess, clip_tokenize\n",
        "    )\n",
        "    n_vis_verified = sum(1 for c in claims\n",
        "                         if c.get('claim_type') in ('visual_object', 'visual_symbol')\n",
        "                         and c.get('validator_status') == 'verified')\n",
        "    print(f'[G-3] Visual validation: {n_vis_verified} visual claims verified.')\n",
        "\n",
        "    # Step 3: OCR validation\n",
        "    claims = validate_all_ocr_claims(claims)\n",
        "\n",
        "    # Step 4: Psych safety validation\n",
        "    claims = validate_all_psych_claims(claims)\n",
        "\n",
        "    # Summary\n",
        "    summary = build_validation_summary(claims)\n",
        "    print(f'[G-3] Validation summary: {summary}')\n",
        "\n",
        "    doc['validated_claims']    = claims\n",
        "    doc['validation_summary']  = summary\n",
        "    return claims, doc\n",
        "\n",
        "print('[G-3] Claim pipeline function defined.')\n",
    ]
}

CELL_PARENT = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# ════════════════════════════════════════════════════════════════\n",
        "# PART G-4 — Parent AI Helper (Template-Based, Verified Claims Only)\n",
        "# + Final Response Judge\n",
        "# ════════════════════════════════════════════════════════════════\n",
        "\n",
        "def run_parent_helper_and_judge(doc, validated_claims, parent_question=''):\n",
        "    \"\"\"\n",
        "    Generate parent-facing answer and run the 10-point final judge.\n",
        "    Returns (parent_output, judgment).\n",
        "    Adds 'parent_output' and 'final_judgment' to doc.\n",
        "    \"\"\"\n",
        "    print('[G-4] Generating parent-facing answer...')\n",
        "    parent_output = generate_parent_answer(doc, validated_claims, parent_question)\n",
        "\n",
        "    print('[G-4] Running final response judge (10 checks)...')\n",
        "    judgment = judge_final_response(parent_output, validated_claims, doc)\n",
        "\n",
        "    status = judgment['final_answer_status']\n",
        "    print(f'[G-4] Judge verdict: {status}')\n",
        "    if judgment.get('issues'):\n",
        "        for issue in judgment['issues']:\n",
        "            print(f'  ISSUE: {issue}')\n",
        "\n",
        "    # If judge rewrote the answer, use the sanitised or fallback version\n",
        "    if status != 'PASS':\n",
        "        if 'sanitised_answer' in judgment:\n",
        "            parent_output = judgment['sanitised_answer']\n",
        "            print('[G-4] Using sanitised answer (post-judge).')\n",
        "        elif 'safe_fallback_answer' in judgment:\n",
        "            parent_output = judgment['safe_fallback_answer']\n",
        "            print('[G-4] Using safe fallback answer (post-judge).')\n",
        "\n",
        "    doc['parent_output']   = parent_output\n",
        "    doc['final_judgment']  = judgment\n",
        "    return parent_output, judgment\n",
        "\n",
        "print('[G-4] Parent helper + judge function defined.')\n",
    ]
}

CELL_PIPELINE_V2 = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# ════════════════════════════════════════════════════════════════\n",
        "# PART G-5 — run_full_pipeline_v2()\n",
        "# Complete v2 pipeline: Parts A–F (existing) + G (new modules)\n",
        "# Old run_full_pipeline() is unchanged and still callable.\n",
        "# ════════════════════════════════════════════════════════════════\n",
        "\n",
        "import json as _json\n",
        "from pathlib import Path as _Path\n",
        "\n",
        "def run_full_pipeline_v2(\n",
        "    image_path: str,\n",
        "    parent_question: str = '',\n",
        "    clip_model=None,\n",
        "    clip_preprocess=None,\n",
        "    clip_tokenize=None,\n",
        "    save_output: bool = True,\n",
        "    output_dir: str = None,\n",
        "):\n",
        "    \"\"\"\n",
        "    Full DOAR v2 pipeline.\n",
        "\n",
        "    Steps:\n",
        "      1. Run existing Parts A-E pipeline to get base doc\n",
        "         (calls run_full_pipeline() which handles A→B→C→D→E)\n",
        "      2. Run v2 extended rules (Tier 1 + Tier 2)\n",
        "      3. Run heuristic emotion estimate (NOT a trained model)\n",
        "      4. Build structured claims\n",
        "      5. Validate claims (numeric / visual / OCR / psych-safety)\n",
        "      6. Generate parent-facing answer (template-based, verified claims only)\n",
        "      7. Run final 10-point judge\n",
        "      8. Return structured output\n",
        "\n",
        "    Returns:\n",
        "      {\n",
        "        'internal_technical_json': { ...full doc... },\n",
        "        'parent_facing_output':    { parent_answer, gentle_questions,\n",
        "                                     safety_note, disclaimer },\n",
        "        'final_judgment':          { status, safe_to_show, issues },\n",
        "        'pipeline_version':        'v2',\n",
        "      }\n",
        "    \"\"\"\n",
        "    print('=' * 65)\n",
        "    print(f'DOAR v2 Pipeline  |  {_Path(image_path).name}')\n",
        "    print('=' * 65)\n",
        "\n",
        "    # ── Step 1: Parts A–E (existing pipeline) ───────────────────\n",
        "    print('[v2] Step 1: Running existing Parts A–E pipeline...')\n",
        "    doc = run_full_pipeline(image_path)  # defined in the existing notebook cells\n",
        "\n",
        "    # ── Step 2: Extended v2 rules ───────────────────────────────\n",
        "    print('[v2] Step 2: Running extended v2 psychological rules...')\n",
        "    doc = run_v2_rules(doc)\n",
        "\n",
        "    # ── Step 3: Heuristic emotion estimate ──────────────────────\n",
        "    print('[v2] Step 3: Feature-based heuristic emotion estimate...')\n",
        "    doc = run_emotion_heuristic(doc)\n",
        "\n",
        "    # ── Step 4–5: Claim builder + validators ────────────────────\n",
        "    print('[v2] Step 4–5: Building and validating claims...')\n",
        "    validated_claims, doc = run_claim_pipeline(\n",
        "        doc, image_path, clip_model, clip_preprocess, clip_tokenize\n",
        "    )\n",
        "\n",
        "    # ── Step 6–7: Parent helper + judge ─────────────────────────\n",
        "    print('[v2] Step 6–7: Generating and judging parent-facing answer...')\n",
        "    parent_output, judgment = run_parent_helper_and_judge(\n",
        "        doc, validated_claims, parent_question\n",
        "    )\n",
        "\n",
        "    # ── Consistency checks ──────────────────────────────────────\n",
        "    print('[v2] Running consistency checks...')\n",
        "    _consistency_issues = _run_consistency_checks(doc, validated_claims, parent_output)\n",
        "    doc['consistency_issues'] = _consistency_issues\n",
        "    if _consistency_issues:\n",
        "        print(f'[v2] {len(_consistency_issues)} consistency issue(s) found:')\n",
        "        for ci in _consistency_issues:\n",
        "            print(f'  - {ci}')\n",
        "    else:\n",
        "        print('[v2] All consistency checks passed.')\n",
        "\n",
        "    # ── Build final structured output ───────────────────────────\n",
        "    final_result = {\n",
        "        'internal_technical_json': {\n",
        "            'analysis_id':    _Path(image_path).stem,\n",
        "            'image_quality':  doc.get('image_quality', {}),\n",
        "            'model_prediction': {\n",
        "                'feature_based_emotional_tendency':\n",
        "                    doc.get('feature_based_emotional_tendency', {}),\n",
        "                'note': 'No trained emotion model is available. '\n",
        "                        'This is a heuristic estimate only.',\n",
        "            },\n",
        "            'visual_features':  {\n",
        "                'color_diversity':   doc.get('color_features', {}).get('color_diversity_count'),\n",
        "                'dominant_color':    doc.get('color_features', {}).get('dominant_color'),\n",
        "                'dark_ratio':        doc.get('color_features', {}).get('dark_dominance'),\n",
        "                'warm_ratio':        doc.get('color_features', {}).get('warm_dominance'),\n",
        "                'empty_space_ratio': doc.get('composition_features', {}).get('empty_space_ratio'),\n",
        "                'content_area_ratio':doc.get('composition_features', {}).get('drawn_content_ratio'),\n",
        "                'placement':         doc.get('composition_features', {}).get('quadrant_bias'),\n",
        "                'stroke_darkness':   doc.get('stroke_features', {}).get('stroke_darkness_estimate'),\n",
        "                'fragmentation_ratio':doc.get('stroke_features', {}).get('fragmentation_ratio'),\n",
        "            },\n",
        "            'detected_objects':  doc.get('detected_objects', []),\n",
        "            'ocr':               {\n",
        "                'detected_text': [r.get('text') for r in doc.get('ocr_results', [])],\n",
        "                'raw_results':   doc.get('ocr_results', []),\n",
        "            },\n",
        "            'psychological_indicators_v1': [\n",
        "                r for r in doc.get('psychological_rule_activations', [])\n",
        "                if r.get('activated')\n",
        "            ],\n",
        "            'psychological_indicators_v2': [\n",
        "                r for r in doc.get('psychological_rule_activations_v2', [])\n",
        "                if r.get('activated')\n",
        "            ],\n",
        "            'theme_scores':      doc.get('theme_scores_v2', []),\n",
        "            'claims':            validated_claims,\n",
        "            'validation_summary':doc.get('validation_summary', {}),\n",
        "            'safety_status': {\n",
        "                'status': 'safe_to_show' if judgment.get('safe_to_show') else 'needs_review',\n",
        "                'reasons': judgment.get('issues', []),\n",
        "            },\n",
        "            'consistency_issues': _consistency_issues,\n",
        "        },\n",
        "        'parent_facing_output': parent_output,\n",
        "        'final_judgment':       judgment,\n",
        "        'pipeline_version':     'v2',\n",
        "    }\n",
        "\n",
        "    # ── Save ────────────────────────────────────────────────────\n",
        "    if save_output:\n",
        "        _out_dir = output_dir or OUTPUT_DIR\n",
        "        os.makedirs(_out_dir, exist_ok=True)\n",
        "        stem = _Path(image_path).stem\n",
        "        out_path = os.path.join(_out_dir, f'{stem}_v2_result.json')\n",
        "        with open(out_path, 'w') as f:\n",
        "            _json.dump(final_result, f, indent=2, default=str)\n",
        "        print(f'[v2] Result saved: {out_path}')\n",
        "\n",
        "    # ── Summary ─────────────────────────────────────────────────\n",
        "    print()\n",
        "    print('─' * 65)\n",
        "    print(f'FINAL STATUS  : {judgment[\"final_answer_status\"]}')\n",
        "    print(f'SAFE TO SHOW  : {judgment[\"safe_to_show\"]}')\n",
        "    vs = doc.get('validation_summary', {})\n",
        "    print(f'CLAIMS        : {vs.get(\"verified_claims\",0)} verified  '\n",
        "          f'{vs.get(\"uncertain_claims\",0)} uncertain  '\n",
        "          f'{vs.get(\"rejected_claims\",0)} rejected')\n",
        "    print('─' * 65)\n",
        "\n",
        "    return final_result\n",
        "\n",
        "\n",
        "# ────────────────────────────────────────────────────────────────\n",
        "# Consistency check helper\n",
        "# ────────────────────────────────────────────────────────────────\n",
        "\n",
        "def _run_consistency_checks(doc, validated_claims, parent_output):\n",
        "    \"\"\"\n",
        "    Run the 15 consistency checks from the specification.\n",
        "    Returns list of issue strings (empty = all passed).\n",
        "    \"\"\"\n",
        "    issues = []\n",
        "    parent_text = parent_output.get('parent_answer', '').lower()\n",
        "\n",
        "    # 1. No unsupported objects in parent answer\n",
        "    verified_labels = {\n",
        "        c.get('evidence', {}).get('label', '').lower()\n",
        "        for c in validated_claims\n",
        "        if c.get('validator_status') == 'verified' and c.get('show_to_user')\n",
        "        and c.get('claim_type') in ('visual_object', 'visual_symbol')\n",
        "    }\n",
        "    rejected_labels = {\n",
        "        c.get('evidence', {}).get('label', '').lower()\n",
        "        for c in validated_claims\n",
        "        if c.get('validator_status') in ('rejected', 'uncertain')\n",
        "        and c.get('claim_type') in ('visual_object', 'visual_symbol')\n",
        "    }\n",
        "    for lbl in rejected_labels:\n",
        "        if lbl and lbl in parent_text:\n",
        "            issues.append(f'Consistency[1]: Rejected/uncertain object \"{lbl}\" appears in parent answer.')\n",
        "\n",
        "    # 2. No uncertain/rejected claims used as facts\n",
        "    for c in validated_claims:\n",
        "        if c.get('validator_status') in ('rejected', 'uncertain') and c.get('show_to_user'):\n",
        "            issues.append(f'Consistency[2]: Claim {c[\"claim_id\"]} has show_to_user=True but status={c[\"validator_status\"]}.')\n",
        "\n",
        "    # 3. No diagnosis or clinical labels\n",
        "    from safety_policy import DIAGNOSTIC_LABELS\n",
        "    for lbl in DIAGNOSTIC_LABELS:\n",
        "        if lbl in parent_text:\n",
        "            issues.append(f'Consistency[3]: Clinical label \"{lbl}\" found in parent answer.')\n",
        "\n",
        "    # 4. No fabricated numbers\n",
        "    from numeric_validator import find_ungrounded_numbers\n",
        "    num_issues = find_ungrounded_numbers(parent_output.get('parent_answer', ''), doc)\n",
        "    for ni in num_issues:\n",
        "        if ni.get('verdict') == 'mismatch':\n",
        "            issues.append(f'Consistency[4]: Fabricated number: {ni[\"reason\"]}')\n",
        "\n",
        "    # 5. Heuristic emotion not presented as trained model output\n",
        "    h = doc.get('feature_based_emotional_tendency', {})\n",
        "    if h.get('method') == 'heuristic' and 'trained model' in parent_text:\n",
        "        issues.append('Consistency[5]: Heuristic emotion estimate presented as trained model output.')\n",
        "\n",
        "    # 6. Final answer uses only verified claims\n",
        "    n_show_unverified = sum(\n",
        "        1 for c in validated_claims\n",
        "        if c.get('show_to_user') and c.get('validator_status') != 'verified'\n",
        "    )\n",
        "    if n_show_unverified > 0:\n",
        "        issues.append(f'Consistency[6]: {n_show_unverified} non-verified claim(s) have show_to_user=True.')\n",
        "\n",
        "    # 7. Disclaimer present\n",
        "    disc = parent_output.get('disclaimer', '') + parent_output.get('safety_note', '')\n",
        "    if 'not diagnostic' not in disc.lower():\n",
        "        issues.append('Consistency[7]: Disclaimer missing \"not diagnostic\" language.')\n",
        "\n",
        "    # 8. v2 psych rules with is_diagnosis=True (should never happen)\n",
        "    for r in doc.get('psychological_rule_activations_v2', []):\n",
        "        if r.get('is_diagnosis') is not False:\n",
        "            issues.append(f'Consistency[8]: Rule {r[\"rule_id\"]} has is_diagnosis != False.')\n",
        "\n",
        "    return issues\n",
        "\n",
        "\n",
        "print('[G-5] run_full_pipeline_v2() defined and ready.')\n",
        "print('      Call: result = run_full_pipeline_v2(image_path, parent_question)')\n",
    ]
}

CELL_DEMO = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# ════════════════════════════════════════════════════════════════\n",
        "# PART G-6 — Demo / Test\n",
        "# Replace IMAGE_PATH with a real image path before running\n",
        "# ════════════════════════════════════════════════════════════════\n",
        "\n",
        "# ── Configure these before running ──────────────────────────────\n",
        "IMAGE_PATH      = \"/content/drive/MyDrive/Masters/Datasets/Combined_Drawing/Sad/s93.jpeg\"\n",
        "PARENT_QUESTION = \"Can you tell me what the drawing shows and whether I should be concerned?\"\n",
        "\n",
        "# ── Optional: pass CLIP model if Part B already loaded it ───────\n",
        "# clip_model_ref = clip_model  # from Part B globals\n",
        "# clip_prep_ref  = clip_preprocess\n",
        "# clip_tok_ref   = clip_tokenize\n",
        "clip_model_ref = None   # set to None if CLIP not in memory\n",
        "clip_prep_ref  = None\n",
        "clip_tok_ref   = None\n",
        "\n",
        "import os\n",
        "if os.path.exists(IMAGE_PATH):\n",
        "    result = run_full_pipeline_v2(\n",
        "        image_path      = IMAGE_PATH,\n",
        "        parent_question = PARENT_QUESTION,\n",
        "        clip_model      = clip_model_ref,\n",
        "        clip_preprocess = clip_prep_ref,\n",
        "        clip_tokenize   = clip_tok_ref,\n",
        "    )\n",
        "\n",
        "    print()\n",
        "    print('╔══ PARENT-FACING OUTPUT ══════════════════════════════════╗')\n",
        "    po = result['parent_facing_output']\n",
        "    print(po.get('parent_answer', ''))\n",
        "    print()\n",
        "    print('Gentle questions to ask your child:')\n",
        "    for q in po.get('gentle_questions', []):\n",
        "        print(f'  • {q}')\n",
        "    print()\n",
        "    print('Safety note:', po.get('safety_note', ''))\n",
        "    print()\n",
        "    print('Disclaimer:', po.get('disclaimer', ''))\n",
        "    print('╚═══════════════════════════════════════════════════════════╝')\n",
        "else:\n",
        "    print(f'[Demo] Image not found: {IMAGE_PATH}')\n",
        "    print('[Demo] Update IMAGE_PATH and re-run this cell.')\n",
    ]
}

# ── Load and update notebook ───────────────────────────────────────────────

with open(NB_PATH) as f:
    nb = json.load(f)

# Safety: check if we already appended (idempotent)
existing_sources = [''.join(c.get('source', [])) for c in nb['cells']]
if any('run_full_pipeline_v2' in s for s in existing_sources):
    print("v2 cells already present — no changes made.")
    sys.exit(0)

new_cells = [
    CELL_SEPARATOR,
    CELL_SETUP,
    CELL_RULES_V2,
    CELL_EMOTION,
    CELL_CLAIMS,
    CELL_PARENT,
    CELL_PIPELINE_V2,
    CELL_DEMO,
]

nb['cells'].extend(new_cells)

with open(NB_PATH, 'w') as f:
    json.dump(nb, f, indent=1)

print(f"Successfully appended {len(new_cells)} cells to notebook.")
print(f"Total cells now: {len(nb['cells'])}")
