"""
Appends the Colab Quick Start section (cells G-7 through G-13) to the notebook.
Safe to run multiple times — checks for existing marker before writing.
"""
import json, sys, os

NB_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                       "DOAR_QA_30_04_26 (2).ipynb")

MARKER = "COLAB_QUICKSTART_V2"   # sentinel string checked before appending

# ── Cell definitions ───────────────────────────────────────────────────────

def md(source_lines):
    return {"cell_type": "markdown", "metadata": {}, "source": source_lines}

def code(source_lines):
    return {"cell_type": "code", "execution_count": None,
            "metadata": {}, "outputs": [], "source": source_lines}


# ── G-7  Section header ────────────────────────────────────────────────────
CELL_HEADER = md([
    "---\n",
    f"<!-- {MARKER} -->\n",
    "## ⚡ Colab Quick Start — DOAR v2 Pipeline\n",
    "\n",
    "**Run these cells from top to bottom in a fresh Colab session.**  \n",
    "They are self-contained: each cell re-imports what it needs so you can\n",
    "re-run individual steps without restarting the runtime.\n",
    "\n",
    "| Step | Cell | What it does |\n",
    "|------|------|--------------|\n",
    "| 1 | G-8 | Install required packages |\n",
    "| 2 | G-9 | Mount Drive & set repo path |\n",
    "| 3 | G-10 | Import v2 modules |\n",
    "| 4 | G-11 | Select / upload one image |\n",
    "| 5 | G-12 | Run `run_full_pipeline_v2()` |\n",
    "| 6 | G-13 | Display outputs |\n",
    "| 7 | G-14 | Compare v1 vs v2 |\n",
])

# ── G-8  Install ───────────────────────────────────────────────────────────
CELL_INSTALL = code([
    "# ════════════════════════════════════════════════════════════════\n",
    "# G-8  INSTALL REQUIRED PACKAGES\n",
    "# Run once per Colab session (runtime restart not needed after this).\n",
    "# Optional heavy packages (CLIP, SAM, PaddleOCR) are installed only\n",
    "# when USE_CLIP / USE_OCR flags are True.  The pipeline runs safely\n",
    "# without them — visual claims become 'uncertain' and OCR is skipped.\n",
    "# ════════════════════════════════════════════════════════════════\n",
    "\n",
    "# ── Flags — set to False to skip heavy optional dependencies ────\n",
    "USE_CLIP    = True   # SAM + CLIP for object detection (needs GPU)\n",
    "USE_OCR     = True   # PaddleOCR\n",
    "USE_SBERT   = True   # Sentence-BERT for attribute retrieval\n",
    "\n",
    "import subprocess, sys\n",
    "\n",
    "def _pip(*pkgs):\n",
    "    subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', *pkgs],\n",
    "                   check=True)\n",
    "\n",
    "# Core (always required)\n",
    "print('[G-8] Installing core dependencies...')\n",
    "_pip('opencv-python-headless', 'Pillow', 'numpy', 'matplotlib')\n",
    "print('      core OK')\n",
    "\n",
    "if USE_CLIP:\n",
    "    print('[G-8] Installing CLIP + SAM (may take ~2 min on first run)...')\n",
    "    _pip('git+https://github.com/openai/CLIP.git')\n",
    "    _pip('git+https://github.com/facebookresearch/segment-anything.git')\n",
    "    print('      CLIP + SAM OK')\n",
    "\n",
    "if USE_OCR:\n",
    "    print('[G-8] Installing PaddleOCR...')\n",
    "    _pip('paddlepaddle', 'paddleocr')\n",
    "    print('      PaddleOCR OK')\n",
    "\n",
    "if USE_SBERT:\n",
    "    print('[G-8] Installing sentence-transformers...')\n",
    "    _pip('sentence-transformers')\n",
    "    print('      sentence-transformers OK')\n",
    "\n",
    "print('[G-8] ✓ All selected packages installed.')\n",
])

# ── G-9  Mount Drive & paths ───────────────────────────────────────────────
CELL_PATHS = code([
    "# ════════════════════════════════════════════════════════════════\n",
    "# G-9  MOUNT GOOGLE DRIVE & SET REPO PATH\n",
    "# Adjust REPO_ROOT if your repo is in a different Drive folder.\n",
    "# ════════════════════════════════════════════════════════════════\n",
    "\n",
    "import os, sys\n",
    "\n",
    "# ── Mount Drive (skip if already mounted) ───────────────────────\n",
    "DRIVE_MOUNTED = os.path.isdir('/content/drive/MyDrive')\n",
    "if not DRIVE_MOUNTED:\n",
    "    from google.colab import drive\n",
    "    drive.mount('/content/drive')\n",
    "    print('[G-9] Drive mounted.')\n",
    "else:\n",
    "    print('[G-9] Drive already mounted.')\n",
    "\n",
    "# ── Repo root — edit this to match your Drive layout ────────────\n",
    "# Option A: notebook cloned/copied into Drive\n",
    "REPO_ROOT = '/content/drive/MyDrive/Masters/DOAR_Project_30_4_26_V2'\n",
    "# Option B: cloned via git in Colab (/content/DOAR)\n",
    "# REPO_ROOT = '/content/DOAR'\n",
    "\n",
    "SRC_DIR    = os.path.join(REPO_ROOT, 'src')\n",
    "CONFIG_DIR = os.path.join(REPO_ROOT, 'config')\n",
    "OUTPUT_DIR = os.path.join(REPO_ROOT, 'outputs_v2')\n",
    "\n",
    "os.makedirs(OUTPUT_DIR, exist_ok=True)\n",
    "\n",
    "# Add src/ to Python path so v2 modules are importable\n",
    "if SRC_DIR not in sys.path:\n",
    "    sys.path.insert(0, SRC_DIR)\n",
    "\n",
    "# Validate layout\n",
    "ok = True\n",
    "for label, path in [('repo root', REPO_ROOT), ('src/', SRC_DIR), ('config/', CONFIG_DIR)]:\n",
    "    exists = os.path.isdir(path)\n",
    "    print(f'  {label:12s} {path}  [{\"OK\" if exists else \"NOT FOUND\"}]')\n",
    "    if not exists:\n",
    "        ok = False\n",
    "\n",
    "if not ok:\n",
    "    print('\\n⚠  One or more paths not found.')\n",
    "    print('   If you cloned the repo with git, run:')\n",
    "    print('     !git clone https://github.com/HHemaly/DOAR /content/DOAR')\n",
    "    print('   Then set REPO_ROOT = \"/content/DOAR\" above and re-run this cell.')\n",
    "else:\n",
    "    print('[G-9] ✓ Paths OK.')\n",
])

# ── G-10  Import v2 modules ────────────────────────────────────────────────
CELL_IMPORTS = code([
    "# ════════════════════════════════════════════════════════════════\n",
    "# G-10  IMPORT v2 MODULES\n",
    "# Each import is wrapped so a missing optional dependency prints a\n",
    "# clear warning instead of crashing the notebook.\n",
    "# ════════════════════════════════════════════════════════════════\n",
    "\n",
    "import importlib, traceback\n",
    "\n",
    "_REQUIRED = [\n",
    "    'safety_policy',\n",
    "    'psychological_rules_v2',\n",
    "    'emotion_heuristic',\n",
    "    'claim_builder',\n",
    "    'numeric_validator',\n",
    "    'visual_claim_validator',\n",
    "    'ocr_validator',\n",
    "    'psych_safety_validator',\n",
    "    'parent_ai_helper',\n",
    "    'final_response_judge',\n",
    "]\n",
    "\n",
    "_loaded = {}\n",
    "_failed = []\n",
    "for _mod in _REQUIRED:\n",
    "    try:\n",
    "        _loaded[_mod] = importlib.import_module(_mod)\n",
    "        print(f'  ✓  {_mod}')\n",
    "    except Exception as _e:\n",
    "        _failed.append(_mod)\n",
    "        print(f'  ✗  {_mod}  —  {_e}')\n",
    "\n",
    "if _failed:\n",
    "    print(f'\\n⚠  {len(_failed)} module(s) failed to import.')\n",
    "    print('   Make sure G-9 ran successfully and SRC_DIR is correct.')\n",
    "    print(f'   SRC_DIR = {SRC_DIR}')\n",
    "else:\n",
    "    print(f'\\n[G-10] ✓ All {len(_loaded)} v2 modules imported.')\n",
    "\n",
    "# Convenient direct references (used in later cells)\n",
    "from safety_policy          import GENERAL_DISCLAIMER\n",
    "from psychological_rules_v2 import evaluate_v2_rules, compute_theme_scores\n",
    "from emotion_heuristic      import estimate_emotional_tendency\n",
    "from claim_builder          import build_all_claims, build_theme_claims\n",
    "from numeric_validator      import validate_all_numeric_claims\n",
    "from visual_claim_validator import validate_all_visual_claims\n",
    "from ocr_validator          import validate_all_ocr_claims\n",
    "from psych_safety_validator import validate_all_psych_claims, build_validation_summary\n",
    "from parent_ai_helper       import generate_parent_answer\n",
    "from final_response_judge   import judge_final_response\n",
    "\n",
    "# Also make sure the G-1..G-5 pipeline helpers are in scope\n",
    "# (they were defined when Parts G-1..G-5 cells were run earlier)\n",
    "_PIPELINE_FNS = ['run_v2_rules', 'run_emotion_heuristic',\n",
    "                  'run_claim_pipeline', 'run_parent_helper_and_judge',\n",
    "                  'run_full_pipeline_v2', 'run_full_pipeline']\n",
    "import IPython as _ipy\n",
    "_ns = _ipy.get_ipython().user_ns\n",
    "_missing_fns = [f for f in _PIPELINE_FNS if f not in _ns]\n",
    "if _missing_fns:\n",
    "    print(f'\\n⚠  Pipeline functions not yet defined: {_missing_fns}')\n",
    "    print('   Please run cells G-0 through G-5 above first,')\n",
    "    print('   then re-run this cell.')\n",
    "else:\n",
    "    print('[G-10] ✓ Pipeline functions are in scope.')\n",
])

# ── G-11  Select image ─────────────────────────────────────────────────────
CELL_IMAGE = code([
    "# ════════════════════════════════════════════════════════════════\n",
    "# G-11  SELECT OR UPLOAD AN IMAGE\n",
    "# Three options — uncomment the one you want.\n",
    "# ════════════════════════════════════════════════════════════════\n",
    "\n",
    "import os\n",
    "from IPython.display import display, Image as IPImage\n",
    "\n",
    "# ── Option A: path to an image already on Drive ─────────────────\n",
    "IMAGE_PATH = '/content/drive/MyDrive/Masters/Datasets/Combined_Drawing/Sad/s93.jpeg'\n",
    "\n",
    "# ── Option B: upload from your computer ─────────────────────────\n",
    "# from google.colab import files as _colab_files\n",
    "# _uploaded = _colab_files.upload()          # opens a file picker\n",
    "# IMAGE_PATH = list(_uploaded.keys())[0]\n",
    "\n",
    "# ── Option C: use a URL ─────────────────────────────────────────\n",
    "# import urllib.request\n",
    "# IMAGE_PATH = '/tmp/test_drawing.jpg'\n",
    "# urllib.request.urlretrieve('https://YOUR_URL_HERE', IMAGE_PATH)\n",
    "\n",
    "# ── Validate ────────────────────────────────────────────────────\n",
    "if os.path.exists(IMAGE_PATH):\n",
    "    size_kb = os.path.getsize(IMAGE_PATH) / 1024\n",
    "    print(f'[G-11] ✓ Image found: {IMAGE_PATH}')\n",
    "    print(f'        Size: {size_kb:.1f} KB')\n",
    "    display(IPImage(IMAGE_PATH, width=400))\n",
    "else:\n",
    "    print(f'[G-11] ✗ Image not found: {IMAGE_PATH}')\n",
    "    print('        Update IMAGE_PATH above and re-run.')\n",
    "\n",
    "# ── Optional: parent question ───────────────────────────────────\n",
    "PARENT_QUESTION = 'Can you tell me what the drawing shows and whether I should be concerned?'\n",
    "print(f'\\nParent question: \"{PARENT_QUESTION}\"')\n",
])

# ── G-12  Run pipeline ─────────────────────────────────────────────────────
CELL_RUN = code([
    "# ════════════════════════════════════════════════════════════════\n",
    "# G-12  RUN run_full_pipeline_v2()\n",
    "# CLIP model references are optional.  If Part B was already run\n",
    "# in this session and clip_model is in scope, pass it in;\n",
    "# otherwise leave as None and visual claims will be 'uncertain'.\n",
    "# ════════════════════════════════════════════════════════════════\n",
    "\n",
    "import IPython as _ipy\n",
    "_ns = _ipy.get_ipython().user_ns\n",
    "\n",
    "# Safely retrieve CLIP references if Part B already loaded them\n",
    "_clip_model     = _ns.get('clip_model',     None)\n",
    "_clip_preprocess= _ns.get('clip_preprocess', None)\n",
    "_clip_tokenize  = _ns.get('clip_tokenize',  None)\n",
    "\n",
    "if _clip_model is None:\n",
    "    print('[G-12] CLIP model not found in session scope.')\n",
    "    print('       Visual claims will be marked uncertain (pipeline still runs).')\n",
    "else:\n",
    "    print('[G-12] CLIP model found — visual claim validation enabled.')\n",
    "\n",
    "# Guard: make sure image was selected in G-11\n",
    "import os\n",
    "if not os.path.exists(IMAGE_PATH):\n",
    "    raise FileNotFoundError(\n",
    "        f'IMAGE_PATH not found: {IMAGE_PATH}\\n'\n",
    "        'Run G-11 first and make sure the image file exists.'\n",
    "    )\n",
    "\n",
    "# ── Run ─────────────────────────────────────────────────────────\n",
    "V2_RESULT = run_full_pipeline_v2(\n",
    "    image_path      = IMAGE_PATH,\n",
    "    parent_question = PARENT_QUESTION,\n",
    "    clip_model      = _clip_model,\n",
    "    clip_preprocess = _clip_preprocess,\n",
    "    clip_tokenize   = _clip_tokenize,\n",
    "    save_output     = True,\n",
    "    output_dir      = OUTPUT_DIR,\n",
    ")\n",
    "\n",
    "print('\\n[G-12] ✓ Pipeline complete.  Results stored in V2_RESULT.')\n",
])

# ── G-13  Display outputs ──────────────────────────────────────────────────
CELL_DISPLAY = code([
    "# ════════════════════════════════════════════════════════════════\n",
    "# G-13  DISPLAY RESULTS\n",
    "#   Section A: Internal technical JSON (collapsible summary)\n",
    "#   Section B: Parent-facing answer\n",
    "#   Section C: Final safety status\n",
    "# ════════════════════════════════════════════════════════════════\n",
    "\n",
    "import json\n",
    "from IPython.display import display, HTML, Markdown\n",
    "\n",
    "def _box(title, content, color='#f0f4f8', border='#90adc6'):\n",
    "    return HTML(f'''\n",
    "        <div style=\"border:1px solid {border};border-radius:8px;\n",
    "                    padding:16px;margin:10px 0;background:{color}\">\n",
    "          <b style=\"font-size:1.05em\">{title}</b>\n",
    "          <pre style=\"white-space:pre-wrap;font-size:0.9em;margin-top:8px\">{content}</pre>\n",
    "        </div>''')\n",
    "\n",
    "# ── A: Internal technical JSON ───────────────────────────────────\n",
    "display(Markdown('### A — Internal Technical JSON'))\n",
    "\n",
    "itj = V2_RESULT.get('internal_technical_json', {})\n",
    "\n",
    "# Image quality\n",
    "iq = itj.get('image_quality', {})\n",
    "display(_box('Image Quality',\n",
    "    f\"quality_score : {iq.get('quality_score', 'n/a')}\\n\"\n",
    "    f\"quality_flag  : {iq.get('quality_flag',  'n/a')}\"\n",
    "))\n",
    "\n",
    "# Emotion estimate\n",
    "mp = itj.get('model_prediction', {}).get('feature_based_emotional_tendency', {})\n",
    "display(_box('Emotional Tendency Estimate (⚠ heuristic only — NOT a trained model)',\n",
    "    f\"estimated_emotion : {mp.get('estimated_emotion', 'n/a')}\\n\"\n",
    "    f\"confidence_label  : {mp.get('confidence_label',  'n/a')}\\n\"\n",
    "    f\"method            : {mp.get('method',            'n/a')}\\n\"\n",
    "    f\"note              : {mp.get('note',              'n/a')}\",\n",
    "    color='#fff8e1', border='#f4c430'\n",
    "))\n",
    "\n",
    "# Visual features\n",
    "vf = itj.get('visual_features', {})\n",
    "vf_text = '\\n'.join(f\"{k:25s}: {v}\" for k, v in vf.items() if v is not None)\n",
    "display(_box('Visual Features', vf_text))\n",
    "\n",
    "# Claim validation summary\n",
    "vs = itj.get('validation_summary', {})\n",
    "display(_box('Claim Validation Summary',\n",
    "    f\"total    : {vs.get('total_claims',    0)}\\n\"\n",
    "    f\"verified : {vs.get('verified_claims', 0)}\\n\"\n",
    "    f\"uncertain: {vs.get('uncertain_claims',0)}\\n\"\n",
    "    f\"rejected : {vs.get('rejected_claims', 0)}\\n\"\n",
    "    f\"shown    : {vs.get('show_to_user_count', 0)}\"\n",
    "))\n",
    "\n",
    "# Activated psychological indicators\n",
    "ind_v1 = itj.get('psychological_indicators_v1', [])\n",
    "ind_v2 = itj.get('psychological_indicators_v2', [])\n",
    "ind_text = ''\n",
    "for r in ind_v1:\n",
    "    ind_text += f\"[v1] {r.get('rule_id','?'):40s} conf={r.get('rule_confidence',0):.3f}\\n\"\n",
    "for r in ind_v2:\n",
    "    t = r.get('tier', '?')\n",
    "    ind_text += f\"[v2 T{t}] {r.get('rule_id','?'):36s} conf={r.get('rule_confidence',0):.3f}  ({r.get('evidence_strength','?')})\\n\"\n",
    "display(_box(f'Activated Psychological Indicators ({len(ind_v1)+len(ind_v2)} total)',\n",
    "    ind_text or '(none activated)'))\n",
    "\n",
    "# Themes\n",
    "themes = itj.get('theme_scores', [])\n",
    "th_text = '\\n'.join(\n",
    "    f\"{t['theme']:45s} score={t['theme_score']:.3f}  rules={t['supporting_rules']}\"\n",
    "    for t in themes\n",
    ") or '(no themes met minimum cluster threshold)'\n",
    "display(_box('Weighted Theme Aggregation', th_text))\n",
    "\n",
    "# Full JSON (collapsed)\n",
    "full_json = json.dumps(itj, indent=2, default=str)\n",
    "display(HTML(f'''\n",
    "    <details style=\"margin:10px 0\">\n",
    "      <summary style=\"cursor:pointer;font-weight:bold\">\n",
    "        📋 Full internal JSON ({len(full_json):,} chars) — click to expand\n",
    "      </summary>\n",
    "      <pre style=\"white-space:pre-wrap;font-size:0.82em;background:#f8f8f8;\n",
    "                  border:1px solid #ddd;padding:12px;border-radius:6px;max-height:400px;\n",
    "                  overflow-y:auto\">{full_json}</pre>\n",
    "    </details>\n",
    "'''))\n",
    "\n",
    "# ── B: Parent-facing answer ──────────────────────────────────────\n",
    "display(Markdown('---\\n### B — Parent-Facing Output'))\n",
    "\n",
    "po = V2_RESULT.get('parent_facing_output', {})\n",
    "\n",
    "display(_box('Parent Answer', po.get('parent_answer', '(none)'),\n",
    "             color='#f0fff0', border='#66bb6a'))\n",
    "\n",
    "questions = po.get('gentle_questions', [])\n",
    "q_text = '\\n'.join(f'• {q}' for q in questions)\n",
    "display(_box('Gentle Questions to Ask Your Child', q_text or '(none)',\n",
    "             color='#e8f5e9', border='#a5d6a7'))\n",
    "\n",
    "display(_box('Safety Note', po.get('safety_note', ''), color='#fff3e0', border='#ffa726'))\n",
    "display(_box('General Disclaimer', po.get('disclaimer', ''), color='#fce4ec', border='#ef9a9a'))\n",
    "\n",
    "# ── C: Final safety status ───────────────────────────────────────\n",
    "display(Markdown('---\\n### C — Final Safety Status'))\n",
    "\n",
    "fj = V2_RESULT.get('final_judgment', {})\n",
    "status   = fj.get('final_answer_status', 'UNKNOWN')\n",
    "safe     = fj.get('safe_to_show', False)\n",
    "n_issues = len(fj.get('issues', []))\n",
    "passed   = fj.get('checks_passed', 0)\n",
    "total    = fj.get('checks_total',  10)\n",
    "\n",
    "status_color = {'PASS': '#e8f5e9', 'REWRITE_REQUIRED': '#fff3e0', 'BLOCK': '#ffebee'}\n",
    "status_border= {'PASS': '#66bb6a', 'REWRITE_REQUIRED': '#ffa726', 'BLOCK': '#ef5350'}\n",
    "sc = status_color.get(status, '#f5f5f5')\n",
    "sb = status_border.get(status, '#aaa')\n",
    "\n",
    "issues_text = '\\n'.join(f'• {i}' for i in fj.get('issues', [])) or '(none)'\n",
    "display(_box(\n",
    "    f'Judge Verdict: {status}   |   Safe to show: {safe}   |   '\n",
    "    f'Checks passed: {passed}/{total}   |   Issues: {n_issues}',\n",
    "    issues_text, color=sc, border=sb\n",
    "))\n",
    "\n",
    "# Consistency issues\n",
    "ci = itj.get('consistency_issues', [])\n",
    "ci_text = '\\n'.join(f'• {i}' for i in ci) or '(none — all consistency checks passed)'\n",
    "display(_box('Consistency Checks', ci_text,\n",
    "             color='#f3e5f5', border='#ba68c8'))\n",
    "\n",
    "print('\\n[G-13] ✓ Display complete.')\n",
])

# ── G-14  Compare v1 vs v2 ─────────────────────────────────────────────────
CELL_COMPARE = code([
    "# ════════════════════════════════════════════════════════════════\n",
    "# G-14  COMPARE  run_full_pipeline()  vs  run_full_pipeline_v2()\n",
    "# Both pipelines analyse the same image so outputs are comparable.\n",
    "# v1 = original Parts A-F only.\n",
    "# v2 = Parts A-F + extended rules + claim validation + parent helper.\n",
    "# ════════════════════════════════════════════════════════════════\n",
    "\n",
    "import json, os\n",
    "from IPython.display import display, HTML, Markdown\n",
    "\n",
    "if not os.path.exists(IMAGE_PATH):\n",
    "    raise FileNotFoundError('Run G-11 first to set IMAGE_PATH.')\n",
    "\n",
    "# ── Run v1 pipeline ──────────────────────────────────────────────\n",
    "print('Running v1 pipeline (Parts A–E)...')\n",
    "doc_v1 = run_full_pipeline(IMAGE_PATH)\n",
    "\n",
    "# ── Gather comparison data ───────────────────────────────────────\n",
    "itj_v2  = V2_RESULT.get('internal_technical_json', {})\n",
    "vs_v2   = itj_v2.get('validation_summary', {})\n",
    "fj_v2   = V2_RESULT.get('final_judgment', {})\n",
    "po_v2   = V2_RESULT.get('parent_facing_output', {})\n",
    "\n",
    "v1_rules = [r for r in doc_v1.get('psychological_rule_activations', []) if r.get('activated')]\n",
    "v2_rules = itj_v2.get('psychological_indicators_v2', [])\n",
    "\n",
    "# ── Render side-by-side table ────────────────────────────────────\n",
    "def _td(text, bg='#fff'):\n",
    "    return f'<td style=\"padding:8px;background:{bg};vertical-align:top\">{text}</td>'\n",
    "\n",
    "def _row(label, v1_val, v2_val, highlight=False):\n",
    "    bg = '#fffde7' if highlight else '#fff'\n",
    "    return f'<tr><td style=\"padding:8px;font-weight:bold\">{label}</td>'\\\n",
    "           f'{_td(str(v1_val), bg)}{_td(str(v2_val), bg)}</tr>'\n",
    "\n",
    "table = f'''\n",
    "<table style=\"border-collapse:collapse;width:100%;font-size:0.9em\">\n",
    "  <thead>\n",
    "    <tr style=\"background:#e3f2fd\">\n",
    "      <th style=\"padding:8px;text-align:left\">Metric</th>\n",
    "      <th style=\"padding:8px\">v1  (Parts A–F)</th>\n",
    "      <th style=\"padding:8px\">v2  (Parts A–G)</th>\n",
    "    </tr>\n",
    "  </thead>\n",
    "  <tbody>\n",
    "    {_row('Psych rules activated (v1 only)',  len(v1_rules), '(v1 rules also run in v2)')}\n",
    "    {_row('New v2 rules activated',           '—',           len(v2_rules))}\n",
    "    {_row('Themes (weighted aggregation)',    '—',           len(itj_v2.get(\"theme_scores\", [])))}\n",
    "    {_row('Structured claims built',          '—',           vs_v2.get('total_claims', 0))}\n",
    "    {_row('Claims verified',                  '—',           vs_v2.get('verified_claims', 0))}\n",
    "    {_row('Claims uncertain',                 '—',           vs_v2.get('uncertain_claims', 0))}\n",
    "    {_row('Claims rejected',                  '—',           vs_v2.get('rejected_claims', 0))}\n",
    "    {_row('Emotion estimate available',       'No',          'Yes (heuristic, low-confidence)')}\n",
    "    {_row('Parent-facing answer',             'No',          'Yes (template, verified claims only)')}\n",
    "    {_row('Final 10-pt judge',                'No',          fj_v2.get(\"final_answer_status\", \"?\"))}\n",
    "    {_row('Safe to show to parent',           'N/A',         str(fj_v2.get(\"safe_to_show\", False)), highlight=True)}\n",
    "    {_row('Disclaimer in output',             'In report',   'Yes (always appended)')}\n",
    "  </tbody>\n",
    "</table>\n",
    "'''\n",
    "display(HTML(table))\n",
    "\n",
    "# ── Show v1 screening summary (first 600 chars) ──────────────────\n",
    "v1_summary = doc_v1.get('screening_summary', '(not available)')\n",
    "display(Markdown('**v1 screening summary (first 600 chars):**'))\n",
    "display(HTML(f'<pre style=\"font-size:0.85em;background:#f8f8f8;padding:12px;'\n",
    "             f'border:1px solid #ddd;border-radius:6px\">{v1_summary[:600]}…</pre>'))\n",
    "\n",
    "# ── Show v2 parent answer ────────────────────────────────────────\n",
    "display(Markdown('**v2 parent-facing answer:**'))\n",
    "display(HTML(f'<pre style=\"font-size:0.85em;background:#f0fff0;padding:12px;'\n",
    "             f'border:1px solid #66bb6a;border-radius:6px\">{po_v2.get(\"parent_answer\", \"\")}'))\n",
    "\n",
    "print('[G-14] ✓ Comparison complete.')\n",
])

# ── Assemble and inject ────────────────────────────────────────────────────

NEW_CELLS = [
    CELL_HEADER,
    CELL_INSTALL,
    CELL_PATHS,
    CELL_IMPORTS,
    CELL_IMAGE,
    CELL_RUN,
    CELL_DISPLAY,
    CELL_COMPARE,
]

with open(NB_PATH) as f:
    nb = json.load(f)

# Idempotency check
all_src = ''.join(''.join(c.get('source', [])) for c in nb['cells'])
if MARKER in all_src:
    print("Quick Start cells already present — no changes made.")
    sys.exit(0)

nb['cells'].extend(NEW_CELLS)

with open(NB_PATH, 'w') as f:
    json.dump(nb, f, indent=1)

print(f"Appended {len(NEW_CELLS)} Quick Start cells.")
print(f"Total cells: {len(nb['cells'])}")
